### ISSUE TITLE
Error on numbers

### ISSUE THREAD

**Issue by diehard98** [udacity/arkit-issues#3]

**Comment by diehard98** [comment]
Section 5 on Lesson 2, the explanation on the bottom of page has error on numbers. 

3. In the attributes inspector tab, modify the width, height, and length of the box to be 0.2, .4, and .02, respectively.

The first number needs to be 0.02 I think.

**Comment by martinwilter** [comment]
@diehard98, thanks for reporting this issue for the [Creating a Scene](https://classroom.udacity.com/nanodegrees/nd116/parts/05b33056-8189-4eb0-9493-d5ee7e94d4d7/modules/b3d6e705-9af9-4045-a50d-ae7508d25bfb/lessons/2eb05804-0597-49d1-ae6d-bc20b717fcf9/concepts/eeeda32c-6545-4c50-9390-5a06c92bd758
) lesson node.

In reviewing the lesson node, I believe

> width, height, and length of the box to be 0.2, .4, and .02, respectively.

is correct for recreating the table as it is shown at the beginning of the video (the legs are square), but you can of course make the legs with any dimensions you prefer.

Can you elaborate on why you think the width should be 0.02 instead of 0.2?

**Comment by diehard98** [comment]
The leg of table should be same width and length (0.02 meter) and height should be 0.4 meter.

In video, the instructor types in 0.02, 0.4, 0.02 in attribute panel in Xcode.
![Screen Shot 2017-10-09 at 3.09.02 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59db7434e365ea00129fdd6a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236454fa6b7191a37bf112224f5f5d5ecc3c4a4356bcbbd671f3e57862804e0ee4856f5821943810abee8a1eb901ba21d91a84b7b5d84dd2f42f67b6d5db1063474f4dcbed5727a29941c95df64ce44a53a61b3f6be2762431.png)

**Comment by martinwilter** [comment]
@diehard98, you are correct. The width value has now been updated and we also added consistent leading zeros throughout the rest of the text:

>3. In the attributes inspector tab, modify the width, height, and length of the box to be 0.02, 0.4, and 0.02, respectively.
<br>

>5. Lastly, change the position of leg 1 to be at (0.22, 0.2, 0.22).
<br>

Thanks again for pointing this out.
